config/routes.rb
Rails.application.routes.draw do
  get '/home', to:'static_pages#home'
  get '/help',to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'

  resources :custom_travels
  resources :users

  root 'static_pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/custom_travel.rb
class CustomTravel < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :custom_travels
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/custom_travels_controller.rb
class CustomTravelsController < ApplicationController
  before_action :set_custom_travel, only: %i[ show edit update destroy ]

  # GET /custom_travels or /custom_travels.json
  def index
    @custom_travels = CustomTravel.all
  end

  # GET /custom_travels/1 or /custom_travels/1.json
  def show
  end

  # GET /custom_travels/new
  def new
    @custom_travel = CustomTravel.new
  end

  # GET /custom_travels/1/edit
  def edit
  end

  # POST /custom_travels or /custom_travels.json
  def create
    @custom_travel = CustomTravel.new(custom_travel_params)

    respond_to do |format|
      if @custom_travel.save
        format.html { redirect_to custom_travel_url(@custom_travel), notice: "Custom travel was successfully created." }
        format.json { render :show, status: :created, location: @custom_travel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @custom_travel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /custom_travels/1 or /custom_travels/1.json
  def update
    respond_to do |format|
      if @custom_travel.update(custom_travel_params)
        format.html { redirect_to custom_travel_url(@custom_travel), notice: "Custom travel was successfully updated." }
        format.json { render :show, status: :ok, location: @custom_travel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @custom_travel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /custom_travels/1 or /custom_travels/1.json
  def destroy
    @custom_travel.destroy

    respond_to do |format|
      format.html { redirect_to custom_travels_url, notice: "Custom travel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_custom_travel
      @custom_travel = CustomTravel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def custom_travel_params
      params.require(:custom_travel).permit(:departure, :destination, :date, :price, :rating, :comments, :physical, :characteristics, :event_bool, :event)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:admin, :name, :surname, :telephon, :email, :encrypted_password, :banned)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title='')
        base_title="Ruby on Rails Tutorial Sample App"
        if page_title.empty?
            base_title
        else
            page_title+ " | "+base_title
        end
    end
end

app/helpers/custom_travels_helper.rb
module CustomTravelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/custom_travels/_custom_travel.html.erb
<div id="<%= dom_id custom_travel %>">
  <p>
    <strong>Departure:</strong>
    <%= custom_travel.departure %>
  </p>

  <p>
    <strong>Destination:</strong>
    <%= custom_travel.destination %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= custom_travel.date %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= custom_travel.price %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= custom_travel.rating %>
  </p>

  <p>
    <strong>Comments:</strong>
    <%= custom_travel.comments %>
  </p>

  <p>
    <strong>Physical:</strong>
    <%= custom_travel.physical %>
  </p>

  <p>
    <strong>Characteristics:</strong>
    <%= custom_travel.characteristics %>
  </p>

  <p>
    <strong>Event bool:</strong>
    <%= custom_travel.event_bool %>
  </p>

  <p>
    <strong>Event:</strong>
    <%= custom_travel.event %>
  </p>

</div>

app/views/custom_travels/_form.html.erb
<%= form_with(model: custom_travel) do |form| %>
  <% if custom_travel.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(custom_travel.errors.count, "error") %> prohibited this custom_travel from being saved:</h2>

      <ul>
        <% custom_travel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :departure, style: "display: block" %>
    <%= form.text_field :departure %>
  </div>

  <div>
    <%= form.label :destination, style: "display: block" %>
    <%= form.text_field :destination %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.text_field :rating %>
  </div>

  <div>
    <%= form.label :comments, style: "display: block" %>
    <%= form.text_area :comments %>
  </div>

  <div>
    <%= form.label :physical, style: "display: block" %>
    <%= form.text_field :physical %>
  </div>

  <div>
    <%= form.label :characteristics, style: "display: block" %>
    <%= form.text_field :characteristics %>
  </div>

  <div>
    <%= form.label :event_bool, style: "display: block" %>
    <%= form.check_box :event_bool %>
  </div>

  <div>
    <%= form.label :event, style: "display: block" %>
    <%= form.text_area :event %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/custom_travels/edit.html.erb
<h1>Editing custom travel</h1>

<%= render "form", custom_travel: @custom_travel %>

<br>

<div>
  <%= link_to "Show this custom travel", @custom_travel %> |
  <%= link_to "Back to custom travels", custom_travels_path %>
</div>

app/views/custom_travels/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Custom travels</h1>

<div id="custom_travels">
  <% @custom_travels.each do |custom_travel| %>
    <%= render custom_travel %>
    <p>
      <%= link_to "Show this custom travel", custom_travel %>
    </p>
  <% end %>
</div>

<%= link_to "New custom travel", new_custom_travel_path %>

app/views/custom_travels/new.html.erb
<h1>New custom travel</h1>

<%= render "form", custom_travel: @custom_travel %>

<br>

<div>
  <%= link_to "Back to custom travels", custom_travels_path %>
</div>

app/views/custom_travels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @custom_travel %>

<div>
  <%= link_to "Edit this custom travel", edit_custom_travel_path(@custom_travel) %> |
  <%= link_to "Back to custom travels", custom_travels_path %>

  <%= button_to "Destroy this custom travel", @custom_travel, method: :delete %>
</div>

app/views/layouts/application.html.erb
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags 'application' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :admin, style: "display: block" %>
    <%= form.check_box :admin %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :surname, style: "display: block" %>
    <%= form.text_field :surname %>
  </div>

  <div>
    <%= form.label :telephon, style: "display: block" %>
    <%= form.text_field :telephon %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :encrypted_password, style: "display: block" %>
    <%= form.text_field :encrypted_password %>
  </div>

  <div>
    <%= form.label :banned, style: "display: block" %>
    <%= form.check_box :banned %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Admin:</strong>
    <%= user.admin %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Surname:</strong>
    <%= user.surname %>
  </p>

  <p>
    <strong>Telephon:</strong>
    <%= user.telephon %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Encrypted password:</strong>
    <%= user.encrypted_password %>
  </p>

  <p>
    <strong>Banned:</strong>
    <%= user.banned %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Telephone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%=user.name %></td>
        <td><%=user.surname %></td>
        <td><%=user.telephon %></td>
        <td><%=user.email %></td>
        <td><%=link_to 'Show',user%></td>
        <td><%=link_to 'Edit',edit_user_path(user)%></td>
        <td><%=link_to 'Destroy',user,method: :delete, data: {confirm: 'Are you sure?'}%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title,"Register") %>
<h1>Register User</h1>

<!--<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>
-->

<p>This will be a signup page for new users.</p>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>